In [7]:
from pathlib import Path
import pandas as pd
import numpy as np

# ============================================
# PROJECT ROOT
# ============================================

ROOT = Path(
    r"D:\My_Project\Analyse\capston Project_2-Global Supply Chain Risk & Logistics"
)

# ============================================
# RAW DATASET PATH
# ============================================

RAW_PATH = (
    ROOT
    / "data"
    / "raw"
    / "global_supply_chain_risk_2026.csv"
)

# ============================================
# CHECK PATH
# ============================================

print("Dataset path:")
print(RAW_PATH)

print("\nFile exists:", RAW_PATH.exists())

# ============================================
# LOAD DATASET
# ============================================

df = pd.read_csv(RAW_PATH)

print("\nDataset loaded successfully!")
print("Shape:", df.shape)

display(df.head())

Dataset path:
D:\My_Project\Analyse\capston Project_2-Global Supply Chain Risk & Logistics\data\raw\global_supply_chain_risk_2026.csv

File exists: True

Dataset loaded successfully!
Shape: (5000, 14)

,Shipment_ID,Date,Origin_Port,Destination_Port,Transport_Mode,Product_Category,Distance_km,Weight_MT,Fuel_Price_Index,Geopolitical_Risk_Score,Weather_Condition,Carrier_Reliability_Score,Lead_Time_Days,Disruption_Occurred
0,SC-10000,2025-10-16,Singapore,Los Angeles,Rail,Textiles,5930.83,197.42,2.43,5.0,Hurricane,0.865,41.39,1
1,SC-10001,2024-04-24,Singapore,Shanghai,Rail,Automotive,14285.36,237.24,2.30,7.5,Storm,0.592,40.92,1
2,SC-10002,2024-01-26,Rotterdam,Los Angeles,Rail,Perishables,11113.91,427.42,1.78,5.6,Rain,0.673,11.54,0
3,SC-10003,2024-10-08,Busan,Hamburg,Rail,Electronics,9180.55,170.66,3.20,0.8,Hurricane,0.832,53.13,1
4,SC-10004,2024-09-07,Busan,Singapore,Air,Perishables,2762.27,434.96,2.77,1.9,Fog,0.741,0.50,1

In [8]:
print("Column names:")

for i, column in enumerate(df.columns, start=1):
    print(i, column)

Column names:
1 Shipment_ID
2 Date
3 Origin_Port
4 Destination_Port
5 Transport_Mode
6 Product_Category
7 Distance_km
8 Weight_MT
9 Fuel_Price_Index
10 Geopolitical_Risk_Score
11 Weather_Condition
12 Carrier_Reliability_Score
13 Lead_Time_Days
14 Disruption_Occurred

In [9]:
display(df.dtypes.to_frame("Data Type"))

                          Data Type
Shipment_ID                     str
Date                            str
Origin_Port                     str
Destination_Port                str
Transport_Mode                  str
Product_Category                str
Distance_km                 float64
Weight_MT                   float64
Fuel_Price_Index            float64
Geopolitical_Risk_Score     float64
Weather_Condition               str
Carrier_Reliability_Score   float64
Lead_Time_Days              float64
Disruption_Occurred           int64

In [10]:
df.isnull().sum()

Shipment_ID                  0
Date                         0
Origin_Port                  0
Destination_Port             0
Transport_Mode               0
Product_Category             0
Distance_km                  0
Weight_MT                    0
Fuel_Price_Index             0
Geopolitical_Risk_Score      0
Weather_Condition            0
Carrier_Reliability_Score    0
Lead_Time_Days               0
Disruption_Occurred          0
dtype: int64

In [11]:
print(df.duplicated().sum())

0

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Shipment_ID                5000 non-null   str
 1   Date                       5000 non-null   str
 2   Origin_Port                5000 non-null   str
 3   Destination_Port           5000 non-null   str
 4   Transport_Mode             5000 non-null   str
 5   Product_Category           5000 non-null   str
 6   Distance_km                5000 non-null   float64
 7   Weight_MT                  5000 non-null   float64
 8   Fuel_Price_Index           5000 non-null   float64
 9   Geopolitical_Risk_Score    5000 non-null   float64
 10  Weather_Condition          5000 non-null   str
 11  Carrier_Reliability_Score  5000 non-null   float64
 12  Lead_Time_Days             5000 non-null   float64
 13  Disruption_Occurred        5000 non-null   int64
dtypes: float64(6), int64(1), str(7)
memory usage: 805.9 KB

In [13]:
df.describe

<bound method NDFrame.describe of      Shipment_ID        Date Origin_Port Destination_Port Transport_Mode  \
0       SC-10000  2025-10-16   Singapore      Los Angeles           Rail
1       SC-10001  2024-04-24   Singapore         Shanghai           Rail
2       SC-10002  2024-01-26   Rotterdam      Los Angeles           Rail
3       SC-10003  2024-10-08       Busan          Hamburg           Rail
4       SC-10004  2024-09-07       Busan        Singapore            Air
...          ...         ...         ...              ...            ...
4995    SC-14995  2025-11-10   Rotterdam            Dubai           Rail
4996    SC-14996  2025-11-23       Dubai         Shanghai            Air
4997    SC-14997  2025-10-18     Antwerp            Busan           Rail
4998    SC-14998  2025-01-29   Singapore            Dubai           Rail
4999    SC-14999  2024-06-01       Dubai         Shanghai            Air

     Product_Category  Distance_km  Weight_MT  Fuel_Price_Index  \
0            Textiles      5930.83     197.42              2.43
1          Automotive     14285.36     237.24              2.30
2         Perishables     11113.91     427.42              1.78
3         Electronics      9180.55     170.66              3.20
4         Perishables      2762.27     434.96              2.77
...               ...          ...        ...               ...
4995      Perishables     13512.26     428.97              3.35
4996      Perishables      2231.02     448.86              1.79
4997  Pharmaceuticals      5253.72     473.41              1.37
4998       Automotive     12328.31     199.35              3.45
4999         Textiles      9161.03     109.35              2.03

      Geopolitical_Risk_Score Weather_Condition  Carrier_Reliability_Score  \
0                         5.0         Hurricane                      0.865
1                         7.5             Storm                      0.592
2                         5.6              Rain                      0.673
3                         0.8         Hurricane                      0.832
4                         1.9               Fog                      0.741
...                       ...               ...                        ...
4995                      8.8               Fog                      0.664
4996                      0.5             Clear                      0.863
4997                      3.0             Clear                      0.962
4998                      4.4             Storm                      0.819
4999                      1.7             Storm                      0.976

      Lead_Time_Days  Disruption_Occurred
0              41.39                    1
1              40.92                    1
2              11.54                    0
3              53.13                    1
4               0.50                    1
...              ...                  ...
4995           20.28                    0
4996            0.50                    0
4997            4.41                    0
4998           31.18                    1
4999            1.43                    1

[5000 rows x 14 columns]>

In [14]:
unique_values = df.nunique().sort_values()

display(
    unique_values.to_frame("Unique Values")
)

                           Unique Values
Disruption_Occurred                    2
Transport_Mode                         4
Weather_Condition                      5
Product_Category                       5
Origin_Port                            8
Destination_Port                       9
Geopolitical_Risk_Score              101
Fuel_Price_Index                     331
Carrier_Reliability_Score            501
Date                                 731
Lead_Time_Days                      2601
Weight_MT                           4785
Distance_km                         4998
Shipment_ID                         5000